<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.billa.sms</groupId>
  <artifactId>micro-services-module</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>micro-services-module</name>

  <modules>
	
	<module>sms-config-server</module>
    <module>sms-eureka-server</module>
	<module>sms-gateway-server</module>
    <module>sms-tracing-app</module>

    <module>sms-web-library</module>
	
    <module>services</module>
	
  </modules>
  
</project>
