server.port=8888

spring.application.name=sms-config-server

spring.config.name=configserver

spring.profiles.active=native

spring.cloud.config.server.native.searchLocations=${user.home}/smsprofiles/

debug=true
